blank_issues_enabled: false
contact_links:
  - name: 📧 Поддержка по email
    url: mailto:support@example.com
    about: Свяжитесь с нами по email для срочных вопросов
  - name: 💬 Telegram поддержка
    url: https://t.me/realestate_support
    about: Получите быструю помощь в Telegram
  - name: 📖 Документация
    url: https://github.com/Pavlentius2007/realestate-platform/wiki
    about: Изучите документацию проекта 